"""Generate HTML/PDF reports from computed analytics facts."""
from __future__ import annotations

import html
import json
from typing import Any

from jinja2 import Template

from ..core.config import settings
from .llm_provider import LLMProvider


REPORT_TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>{{ title }}</title>
  <style>
    body { font-family: Inter, Segoe UI, Arial, sans-serif; color: #111827; margin: 40px; line-height: 1.55; }
    h1 { color: #4f46e5; font-size: 30px; margin-bottom: 8px; }
    h2 { color: #1f2937; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; margin-top: 28px; }
    .meta { color: #6b7280; font-size: 13px; margin-bottom: 28px; }
    ul { padding-left: 22px; }
    pre { background: #f8fafc; padding: 14px; border-radius: 8px; overflow-x: auto; }
  </style>
</head>
<body>
  <h1>{{ title }}</h1>
  <div class="meta">Generated by DataVerse AI from computed dataset facts.</div>
  {% for section in sections %}
    <h2>{{ section.title }}</h2>
    <div>{{ section.body }}</div>
  {% endfor %}
</body>
</html>"""
)


class ReportGenerator:
    """Use Gemini for report language when available; deterministic HTML/PDF fallback otherwise."""

    def __init__(self, llm_provider: LLMProvider | None = None) -> None:
        self.llm_provider = llm_provider or LLMProvider(provider="gemini")

    async def generate(self, *, title: str, facts: dict[str, Any], xai_output: dict[str, Any] | None = None) -> dict[str, bytes | str]:
        sections = await self._sections(title=title, facts=facts, xai_output=xai_output or {})
        html_text = REPORT_TEMPLATE.render(title=html.escape(title), sections=sections)
        pdf_bytes = self._simple_pdf(title, sections)
        return {"html": html_text, "pdf": pdf_bytes}

    async def _sections(self, *, title: str, facts: dict[str, Any], xai_output: dict[str, Any]) -> list[dict[str, str]]:
        deterministic = self._deterministic_sections(facts, xai_output)
        if not self.llm_provider.is_configured():
            return deterministic

        prompt = (
            "Write a professional analytics report from computed facts only. "
            "Return JSON with key sections, an array of objects with title and body. "
            "Required section titles: Title, Dataset overview, Data quality, Key metrics, Trends, "
            "Business insights, Prediction readiness/results, XAI explanation, Limitations, "
            "Recommendations, Appendix: column profile. Do not invent numbers.\n"
            f"Report title: {title}\n"
            f"Facts JSON:\n{json.dumps(_safe_facts(facts, xai_output), default=str)[:14000]}"
        )
        text = await self.llm_provider.generate(
            prompt,
            system_prompt="Use Gemini for final report generation only. Return strict JSON.",
            json_mode=True,
        )
        if not text:
            return deterministic
        try:
            payload = json.loads(_strip_fence(text))
            sections = payload.get("sections")
            if isinstance(sections, list) and sections:
                return [
                    {"title": str(item.get("title", "Section")), "body": html.escape(str(item.get("body", ""))).replace("\n", "<br />")}
                    for item in sections
                    if isinstance(item, dict)
                ]
        except Exception:
            return deterministic
        return deterministic

    def _deterministic_sections(self, facts: dict[str, Any], xai_output: dict[str, Any]) -> list[dict[str, str]]:
        profile = facts.get("dataset_profile") or {}
        quality = facts.get("data_quality") or {}
        business = facts.get("business_metrics") or {}
        prediction = facts.get("prediction") or {}
        xai = xai_output or facts.get("xai") or {}
        semantic = facts.get("semantic_map") or {}
        sections = [
            ("Title", "This report summarizes the uploaded dataset using computed analytics facts."),
            ("Dataset overview", f"Rows: {profile.get('row_count', 0)}. Columns: {profile.get('column_count', 0)}. Detected type: {semantic.get('dataset_type', profile.get('dataset_type', 'generic_tabular'))}."),
            ("Data quality", f"Missing cells: {quality.get('missing_cells', quality.get('total_missing', 0))}. Duplicate rows: {quality.get('duplicate_rows', 0)}. Quality score: {quality.get('data_quality_score', quality.get('score', 'n/a'))}."),
            ("Key metrics", json.dumps({key: business.get(key) for key in ('total_revenue', 'total_quantity', 'total_profit', 'gross_margin', 'transaction_count') if business.get(key) is not None}, default=str)),
            ("Trends", f"Trend series detected: {len((facts.get('trends') or {}).get('series', []))}."),
            ("Business insights", " ".join(facts.get("key_insights") or []) or facts.get("executive_summary") or "No narrative insights were generated."),
            ("Prediction readiness/results", prediction.get("reason") or prediction.get("status", "Prediction was not run.")),
            ("XAI explanation", xai.get("plain_english_explanation") or "XAI was not available for this dataset/model."),
            ("Limitations", " ".join(facts.get("warnings") or []) or "No major automated warnings."),
            ("Recommendations", " ".join(facts.get("recommendations") or []) or "Review the dataset and rerun analysis after cleaning issues."),
            ("Appendix: column profile", json.dumps(profile.get("columns", []), default=str)[:4000]),
        ]
        return [{"title": title, "body": html.escape(body).replace("\n", "<br />")} for title, body in sections]

    def _simple_pdf(self, title: str, sections: list[dict[str, str]]) -> bytes:
        """Produce a minimal valid PDF without requiring optional PDF dependencies."""
        lines = [title, "Generated by DataVerse AI", ""]
        for section in sections:
            lines.extend([section["title"], _plain(section["body"]), ""])
        text = "\n".join(lines)[:9000]
        escaped = text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
        stream = f"BT /F1 11 Tf 50 780 Td 14 TL ({escaped}) Tj ET"
        objects = [
            "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
            "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
            "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj",
            "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
            f"5 0 obj << /Length {len(stream.encode('latin-1', errors='ignore'))} >> stream\n{stream}\nendstream endobj",
        ]
        body = "%PDF-1.4\n" + "\n".join(objects) + "\n"
        offsets = [0]
        cursor = len("%PDF-1.4\n")
        for obj in objects:
            offsets.append(cursor)
            cursor += len(obj) + 1
        xref_at = len(body)
        xref = ["xref", f"0 {len(objects) + 1}", "0000000000 65535 f "]
        xref.extend(f"{offset:010d} 00000 n " for offset in offsets[1:])
        trailer = f"\ntrailer << /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF"
        return (body + "\n".join(xref) + trailer).encode("latin-1", errors="ignore")


def _safe_facts(facts: dict[str, Any], xai_output: dict[str, Any]) -> dict[str, Any]:
    return {
        "dataset_profile": facts.get("dataset_profile"),
        "semantic_map": facts.get("semantic_map"),
        "business_metrics": facts.get("business_metrics"),
        "data_quality": facts.get("data_quality"),
        "trends": facts.get("trends"),
        "prediction": facts.get("prediction"),
        "xai": xai_output or facts.get("xai"),
        "warnings": facts.get("warnings"),
        "recommendations": facts.get("recommendations"),
    }


def _strip_fence(text: str) -> str:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
    return cleaned


def _plain(value: str) -> str:
    return value.replace("<br />", "\n").replace("&quot;", '"').replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
