"""Generate self-contained HTML and PDF reports from computed analytics facts."""
from __future__ import annotations

import html
import io
import json
import math
import re
from datetime import datetime, timezone
from typing import Any

from jinja2 import Template

from ..core.config import settings
from .data_quality import validate_chart_spec
from .llm_provider import LLMProvider


PALETTE = ["#8b5cf6", "#3b82f6", "#0ea5e9", "#10b981", "#f59e0b", "#f43f5e", "#14b8a6", "#a855f7"]

REPORT_TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>{{ title }}</title>
  <style>
    :root { color-scheme: light; --ink:#111827; --muted:#64748b; --line:#dbe3ef; --violet:#8b5cf6; --blue:#3b82f6; --sky:#0ea5e9; --emerald:#10b981; --amber:#f59e0b; --rose:#f43f5e; }
    * { box-sizing: border-box; }
    body { margin: 0; font-family: Inter, Segoe UI, Arial, sans-serif; color: var(--ink); background: #f8fafc; line-height: 1.55; }
    .cover { padding: 44px 52px 36px; color: white; background: radial-gradient(circle at 20% 20%, rgba(139,92,246,.45), transparent 32%), linear-gradient(135deg, #0b1326, #172554 58%, #312e81); }
    h1 { font-size: 34px; margin: 0 0 12px; letter-spacing: 0; }
    h2 { font-size: 20px; margin: 0 0 14px; color: #172554; }
    h3 { font-size: 14px; margin: 0 0 8px; color: #334155; }
    .meta { color: #dbeafe; font-size: 13px; display: flex; gap: 18px; flex-wrap: wrap; }
    .page { max-width: 1120px; margin: 0 auto; padding: 28px; }
    .section { background: white; border: 1px solid var(--line); border-radius: 14px; padding: 22px; margin: 0 0 20px; box-shadow: 0 10px 30px rgba(15,23,42,.06); }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 14px; }
    .card { border: 1px solid #e2e8f0; border-radius: 12px; padding: 14px; background: linear-gradient(180deg, #ffffff, #f8fafc); }
    .label { font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: .04em; }
    .value { font-size: 22px; font-weight: 800; color: #0f172a; margin-top: 3px; }
    .chart-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 18px; }
    .chart { border: 1px solid #e2e8f0; border-radius: 12px; padding: 14px; background: #fff; overflow: hidden; }
    svg { width: 100%; height: auto; display: block; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th { text-align: left; background: #eef2ff; color: #312e81; }
    th, td { padding: 8px 10px; border-bottom: 1px solid #e2e8f0; white-space: nowrap; }
    ul { margin: 0; padding-left: 20px; }
    li { margin: 5px 0; }
    .muted { color: var(--muted); }
    .warning { color: #9f1239; }
    @media print {
      body { background: white; }
      .section, .chart { break-inside: avoid; box-shadow: none; }
      .cover { break-after: page; }
    }
  </style>
</head>
<body>
  <header class="cover">
    <h1>{{ title }}</h1>
    <div class="meta">
      <span>Generated by DataVerse AI</span>
      <span>{{ generated_at }}</span>
      <span>{{ filename }}</span>
      <span>{{ rows }} rows / {{ cols }} columns</span>
    </div>
  </header>
  <main class="page">
    <section class="section">
      <h2>{{ metric_title }}</h2>
      <div class="grid">
        {% for metric in metrics %}
          <div class="card"><div class="label">{{ metric.label }}</div><div class="value">{{ metric.value }}</div></div>
        {% endfor %}
      </div>
    </section>
    <section class="section">
      <h2>Executive Summary</h2>
      <ul>{% for item in insights %}<li>{{ item }}</li>{% endfor %}</ul>
    </section>
    {% if charts %}
      <section class="section">
        <h2>Charts</h2>
        <div class="chart-grid">
          {% for chart in charts %}
            <div class="chart"><h3>{{ chart.title }}</h3>{{ chart.svg }}</div>
          {% endfor %}
        </div>
      </section>
    {% endif %}
    {% for table in tables %}
      <section class="section">
        <h2>{{ table.title }}</h2>
        <table>
          <thead><tr>{% for column in table.columns %}<th>{{ column }}</th>{% endfor %}</tr></thead>
          <tbody>
            {% for row in table.rows %}
              <tr>{% for column in table.columns %}<td>{{ row.get(column, "") }}</td>{% endfor %}</tr>
            {% endfor %}
          </tbody>
        </table>
      </section>
    {% endfor %}
    {% for section in sections %}
      <section class="section">
        <h2>{{ section.title }}</h2>
        <div>{{ section.body }}</div>
      </section>
    {% endfor %}
  </main>
</body>
</html>"""
)


class ReportGenerator:
    """Build rich deterministic reports, with optional LLM-polished sections."""

    def __init__(self, llm_provider: LLMProvider | None = None) -> None:
        provider = settings.LLM_PROVIDER if settings.USE_LLM_NARRATION else "deterministic"
        self.llm_provider = llm_provider or LLMProvider(provider=provider)

    async def generate(self, *, title: str, facts: dict[str, Any], xai_output: dict[str, Any] | None = None) -> dict[str, bytes | str]:
        xai = xai_output or {}
        sections = await self._sections(title=title, facts=facts, xai_output=xai)
        html_text = self._render_html(title, facts, xai, sections)
        pdf_bytes = self._pdf(title, facts, xai, sections)
        return {"html": html_text, "pdf": pdf_bytes}

    def _render_html(self, title: str, facts: dict[str, Any], xai_output: dict[str, Any], sections: list[dict[str, str]]) -> str:
        profile = facts.get("dataset_profile") or {}
        metrics = self._metric_cards(facts)
        valid_charts = [chart for chart in (facts.get("charts") or []) if _chart_is_renderable(chart)][:10]
        charts = [{"title": html.escape(str(chart.get("title", "Chart"))), "svg": self._chart_svg(chart)} for chart in valid_charts]
        tables = self._tables(facts)
        insights = [html.escape(str(item)) for item in (facts.get("key_insights") or [])[:12]]
        if not insights:
            insights = [html.escape(str(facts.get("executive_summary") or "Computed analytics report is ready."))]
        return REPORT_TEMPLATE.render(
            title=html.escape(title),
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            filename=html.escape(str(facts.get("filename") or profile.get("filename") or "uploaded dataset")),
            rows=profile.get("row_count", 0),
            cols=profile.get("column_count", 0),
            metric_title="Dataset Summary Cards" if _is_food_dataset(facts) else "Summary Cards",
            metrics=metrics,
            insights=insights,
            charts=charts,
            tables=tables,
            sections=sections,
        )

    async def _sections(self, *, title: str, facts: dict[str, Any], xai_output: dict[str, Any]) -> list[dict[str, str]]:
        deterministic = self._deterministic_sections(facts, xai_output)
        if _is_food_dataset(facts):
            return deterministic
        if not self.llm_provider.is_configured():
            return deterministic
        prompt = (
            "Write a professional analytics report from computed facts only. "
            "Return JSON with key sections, an array of objects with title and body. "
            "Do not invent numbers. Keep bodies concise.\n"
            f"Report title: {title}\n"
            f"Facts JSON:\n{json.dumps(_safe_facts(facts, xai_output), default=str)[:14000]}"
        )
        text = await self.llm_provider.generate(
            prompt,
            system_prompt="Use computed facts only. Return strict JSON.",
            json_mode=True,
        )
        if not text:
            return deterministic
        try:
            payload = json.loads(_strip_fence(text))
            sections = payload.get("sections")
            if isinstance(sections, list) and sections:
                return [
                    {"title": html.escape(str(item.get("title", "Section"))), "body": html.escape(str(item.get("body", ""))).replace("\n", "<br />")}
                    for item in sections
                    if isinstance(item, dict)
                ]
        except Exception:
            return deterministic
        return deterministic

    def _deterministic_sections(self, facts: dict[str, Any], xai_output: dict[str, Any]) -> list[dict[str, str]]:
        profile = facts.get("dataset_profile") or {}
        quality = facts.get("data_quality") or {}
        business = facts.get("business_metrics") or {}
        product = facts.get("product_analysis") or {}
        food = facts.get("food_analysis") or {}
        prediction = facts.get("prediction") or {}
        xai = xai_output or facts.get("xai") or {}
        semantic = facts.get("semantic_map") or {}
        query_plan = facts.get("query_plan") or {}
        query_answer = facts.get("query_answer") or {}
        if str(query_plan.get("intent")) == "total_sales":
            sections = [
                ("Direct Answer", query_answer.get("answer") or "Total sales overview is ready."),
                ("Dataset Overview", f"Rows: {profile.get('row_count', 0)}. Columns: {profile.get('column_count', 0)}. Detected type: {semantic.get('dataset_type', profile.get('dataset_type', 'generic_tabular'))}."),
                ("Data Quality", f"Missing cells: {quality.get('missing_cells', quality.get('total_missing', 0))}. Duplicate rows: {quality.get('duplicate_rows', 0)}. Quality score: {quality.get('data_quality_score', quality.get('score', 'n/a'))}."),
                ("Top Context", _focused_sales_context(business)),
                ("Recommendations", " ".join(facts.get("recommendations") or query_answer.get("recommendations") or []) or "Ask for month, category, or region breakdowns for more detail."),
                ("Limitations", " ".join(facts.get("warnings") or []) or "No major automated warnings."),
            ]
            return [{"title": title, "body": html.escape(str(body)).replace("\n", "<br />")} for title, body in sections]
        if _is_food_dataset(facts):
            sections = [
                ("Dataset Overview", f"Rows: {profile.get('row_count', 0)}. Columns: {profile.get('column_count', 0)}. Detected as a food classification / food catalog dataset."),
                ("Data Quality", f"Missing cells: {quality.get('missing_cells', quality.get('total_missing', 0))}. Duplicate rows: {quality.get('duplicate_rows', 0)}. Quality score: {quality.get('data_quality_score', quality.get('score', 'n/a'))}."),
                ("Dataset Limitations", (food.get("warnings") or ["This dataset does not contain sales, revenue, profit, quantity, order date, or transaction columns. Therefore revenue analysis, most-sold product analysis, sales trends, and profit analysis cannot be calculated."])[0]),
                ("Food Frequency Analysis", " ".join(food.get("insights", [])) or self._product_section(product)),
                ("Calories Statistics", json.dumps(food.get("calories_stats") or {}, default=str)),
                ("Duplicate Row Warning", f"Duplicate rows detected: {quality.get('duplicate_rows', 0)}."),
                ("Prediction/Model Summary", _prediction_text(prediction)),
                ("XAI Explanation", _xai_text(xai, prediction)),
                ("Recommendations", " ".join(facts.get("recommendations") or food.get("recommendations") or []) or "Review catalog frequencies and collect transaction fields before sales analysis."),
                ("Next Questions", " ".join(facts.get("next_questions") or food.get("next_questions") or []) or "Ask about category, cuisine, ingredient, spice level, or calories patterns."),
            ]
            return [{"title": title, "body": html.escape(str(body)).replace("\n", "<br />")} for title, body in sections]
        sections = [
            ("Dataset Overview", f"Rows: {profile.get('row_count', 0)}. Columns: {profile.get('column_count', 0)}. Detected type: {semantic.get('dataset_type', profile.get('dataset_type', 'generic_tabular'))}."),
            ("Data Quality", f"Missing cells: {quality.get('missing_cells', quality.get('total_missing', 0))}. Duplicate rows: {quality.get('duplicate_rows', 0)}. Quality score: {quality.get('data_quality_score', quality.get('score', 'n/a'))}."),
            ("Key Metrics", json.dumps({key: business.get(key) for key in ("total_revenue", "total_quantity", "total_profit", "gross_margin", "transaction_count") if business.get(key) is not None}, default=str)),
            ("Trending Products", self._product_section(product)),
            ("XAI Explanation", xai.get("plain_english_explanation") or "XAI was not available for this dataset/model."),
            ("Limitations and Warnings", " ".join(facts.get("warnings") or []) or "No major automated warnings."),
            ("Recommendations", " ".join(facts.get("recommendations") or []) or "Review the dataset and rerun analysis after cleaning issues."),
            ("Next Questions", " ".join(facts.get("next_questions") or []) or "Ask a focused follow-up question about a product, category, region, or trend."),
            ("Appendix: Column Profile", json.dumps(profile.get("columns", []), default=str)[:4000]),
            ("Prediction Readiness/Results", prediction.get("reason") or prediction.get("status", "Prediction was not run.")),
        ]
        return [{"title": title, "body": html.escape(str(body)).replace("\n", "<br />")} for title, body in sections]

    def _metric_cards(self, facts: dict[str, Any]) -> list[dict[str, str]]:
        if facts.get("kpis"):
            return [{"label": str(item.get("label", "Metric")), "value": html.escape(_fmt(item.get("value")))} for item in facts.get("kpis", [])]
        if _is_food_dataset(facts):
            profile = facts.get("dataset_profile") or {}
            quality = facts.get("data_quality") or {}
            food = facts.get("food_analysis") or {}
            calories = food.get("calories_stats") or {}
            items = [
                ("Rows", profile.get("row_count")),
                ("Columns", profile.get("column_count")),
                ("Missing Cells", quality.get("missing_cells")),
                ("Duplicate Rows", quality.get("duplicate_rows")),
                ("Mean Calories", calories.get("mean")),
                ("Quality Score", quality.get("data_quality_score")),
            ]
            return [{"label": label, "value": html.escape(_fmt(value))} for label, value in items if value is not None]
        business = facts.get("business_metrics") or {}
        quality = facts.get("data_quality") or {}
        items = [
            ("Total Revenue", business.get("total_revenue")),
            ("Total Quantity", business.get("total_quantity")),
            ("Total Profit", business.get("total_profit")),
            ("Gross Margin", f"{business.get('gross_margin')}%" if business.get("gross_margin") is not None else None),
            ("Transactions", business.get("transaction_count")),
            ("Quality Score", quality.get("data_quality_score")),
        ]
        return [{"label": label, "value": html.escape(_fmt(value))} for label, value in items if value is not None]

    def _tables(self, facts: dict[str, Any]) -> list[dict[str, Any]]:
        tables = []
        intent = str((facts.get("query_plan") or {}).get("intent") or "")
        if intent == "total_sales":
            source_tables = list((facts.get("query_answer") or {}).get("tables", []))
        else:
            source_tables = [
                *(facts.get("food_analysis") or {}).get("tables", []),
                *(facts.get("product_analysis") or {}).get("tables", []),
                *((facts.get("query_answer") or {}).get("tables", [])),
            ]
        for table in source_tables:
            if isinstance(table, dict) and table.get("rows"):
                columns = [str(column) for column in table.get("columns", [])]
                rows = [
                    {column: html.escape(_fmt(row.get(column))) for column in columns}
                    for row in table.get("rows", [])[:12]
                    if isinstance(row, dict)
                ]
                tables.append({"title": html.escape(str(table.get("title", "Table"))), "columns": columns, "rows": rows})
        return tables[:6]

    def _product_section(self, product: dict[str, Any]) -> str:
        top = product.get("top_products_by_revenue") or []
        growth = product.get("fastest_growing_products") or []
        lines = []
        if top:
            lines.append(f"Top revenue product: {top[0].get('product')} with {top[0].get('revenue')}.")
        if growth:
            lines.append(f"Fastest growth: {growth[0].get('product')} increased by {growth[0].get('absolute_growth')}.")
        return " ".join(lines) or "No product trend chart could be computed from the available columns."

    def _chart_svg(self, chart: dict[str, Any]) -> str:
        chart_type = str(chart.get("type", "bar")).lower()
        if chart_type == "confusion_matrix":
            return _confusion_matrix_svg(chart)
        if chart_type == "line":
            return _line_svg(chart)
        if chart_type in {"pie", "donut"}:
            return _donut_svg(chart, donut=chart_type == "donut")
        return _bar_svg(chart)

    def _pdf(self, title: str, facts: dict[str, Any], xai_output: dict[str, Any], sections: list[dict[str, str]]) -> bytes:
        try:
            return self._reportlab_pdf(title, facts, xai_output, sections)
        except Exception:
            return self._fallback_pdf(title, facts, sections)

    def _reportlab_pdf(self, title: str, facts: dict[str, Any], xai_output: dict[str, Any], sections: list[dict[str, str]]) -> bytes:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=0.55 * inch, leftMargin=0.55 * inch, topMargin=0.55 * inch, bottomMargin=0.55 * inch)
        styles = getSampleStyleSheet()
        story: list[Any] = []
        story.append(Paragraph(html.escape(title), styles["Title"]))
        story.append(Paragraph("Generated by DataVerse AI from computed dataset facts.", styles["Normal"]))
        story.append(Spacer(1, 12))
        metric_rows = [["Metric", "Value"]] + [[item["label"], item["value"]] for item in self._metric_cards(facts)]
        story.append(Table(metric_rows, hAlign="LEFT", style=TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2ff")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#312e81")),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#dbe3ef")),
            ("PADDING", (0, 0), (-1, -1), 6),
        ])))
        story.append(Spacer(1, 12))
        for chart in (facts.get("charts") or [])[:6]:
            if not _chart_is_renderable(chart):
                continue
            story.append(Paragraph(html.escape(str(chart.get("title", "Chart"))), styles["Heading2"]))
            drawing = _reportlab_chart_drawing(chart)
            if drawing is not None:
                story.append(drawing)
                story.append(Spacer(1, 8))
            rows = _chart_rows(chart)
            if rows:
                story.append(Table(rows, hAlign="LEFT", repeatRows=1, style=TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
                    ("PADDING", (0, 0), (-1, -1), 5),
                ])))
                story.append(Spacer(1, 10))
        for table in self._tables(facts)[:4]:
            story.append(Paragraph(table["title"], styles["Heading2"]))
            rows = [table["columns"]] + [[row.get(column, "") for column in table["columns"]] for row in table["rows"]]
            story.append(Table(rows, hAlign="LEFT", repeatRows=1, style=TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2ff")),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
                ("PADDING", (0, 0), (-1, -1), 5),
            ])))
            story.append(Spacer(1, 10))
        for section in sections:
            story.append(Paragraph(section["title"], styles["Heading2"]))
            story.append(Paragraph(_plain(section["body"]), styles["BodyText"]))
            story.append(Spacer(1, 8))
        doc.build(story)
        return buffer.getvalue()

    def _fallback_pdf(self, title: str, facts: dict[str, Any], sections: list[dict[str, str]]) -> bytes:
        lines = [title, "Generated by DataVerse AI", ""]
        for item in self._metric_cards(facts):
            lines.append(f"{item['label']}: {item['value']}")
        lines.append("")
        for chart in (facts.get("charts") or [])[:8]:
            if not _chart_is_renderable(chart):
                continue
            lines.append(str(chart.get("title", "Chart")))
            for row in (chart.get("data") or [])[:8]:
                lines.append("  " + ", ".join(f"{key}: {_fmt(value)}" for key, value in row.items()))
            lines.append("")
        for section in sections:
            lines.extend([section["title"], _plain(section["body"]), ""])
        return _manual_pdf(lines)


def _bar_svg(chart: dict[str, Any]) -> str:
    raw_data = chart.get("data") or []
    data = raw_data[:10] if isinstance(raw_data, list) else []
    x_key = chart.get("x_key") or chart.get("x")
    y_key = chart.get("y_key") or chart.get("y")
    values = [abs(_num(row.get(y_key))) for row in data if isinstance(row, dict)]
    max_value = _chart_scale(values)
    rows = []
    for idx, row in enumerate(data):
        value = _num(row.get(y_key))
        width = max(2, min(260, abs(value) / max_value * 260))
        y = 28 + idx * 28
        label = html.escape(_truncate(_fmt(row.get(x_key)), 24))
        color = PALETTE[idx % len(PALETTE)] if value >= 0 else "#f43f5e"
        rows.append(f'<text x="0" y="{y + 10}" font-size="10" fill="#475569">{label}</text><rect x="150" y="{y}" width="{width:.1f}" height="16" rx="5" fill="{color}"/><text x="{155 + width:.1f}" y="{y + 12}" font-size="10" fill="#0f172a">{html.escape(_fmt(value))}</text>')
    height = max(80, 36 + len(data) * 28)
    return f'<svg viewBox="0 0 460 {height}" role="img">{"".join(rows)}</svg>'


def _confusion_matrix_svg(chart: dict[str, Any]) -> str:
    data = [row for row in (chart.get("data") or []) if isinstance(row, dict)]
    actual_labels = sorted({str(row.get("actual")) for row in data})
    predicted_labels = sorted({str(row.get("predicted")) for row in data})
    counts = {(str(row.get("actual")), str(row.get("predicted"))): _num(row.get("count")) for row in data}
    max_count = max(counts.values() or [1])
    cell = 34
    left = 100
    top = 42
    width = left + max(1, len(predicted_labels)) * cell + 20
    height = top + max(1, len(actual_labels)) * cell + 34
    parts = [
        '<text x="0" y="18" font-size="11" fill="#475569">Actual vs predicted labels</text>',
    ]
    for col_idx, predicted in enumerate(predicted_labels):
        x = left + col_idx * cell
        parts.append(f'<text x="{x + 2}" y="34" font-size="8" fill="#475569">{html.escape(_truncate(predicted, 8))}</text>')
    for row_idx, actual in enumerate(actual_labels):
        y = top + row_idx * cell
        parts.append(f'<text x="0" y="{y + 21}" font-size="8" fill="#475569">{html.escape(_truncate(actual, 16))}</text>')
        for col_idx, predicted in enumerate(predicted_labels):
            x = left + col_idx * cell
            count = counts.get((actual, predicted), 0.0)
            opacity = 0.12 + (count / max_count * 0.78 if max_count else 0)
            parts.append(f'<rect x="{x}" y="{y}" width="{cell - 2}" height="{cell - 2}" rx="4" fill="#3b82f6" opacity="{opacity:.2f}"/>')
            parts.append(f'<text x="{x + cell / 2 - 4}" y="{y + 20}" font-size="9" fill="#0f172a">{html.escape(_fmt(count))}</text>')
    return f'<svg viewBox="0 0 {width} {height}" role="img">{"".join(parts)}</svg>'


def _line_svg(chart: dict[str, Any]) -> str:
    raw_data = chart.get("data") or []
    data = raw_data if isinstance(raw_data, list) else []
    x_key = chart.get("x_key") or chart.get("x")
    y_key = chart.get("y_key") or chart.get("y")
    series_key = chart.get("series_key")
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in data:
        if not isinstance(row, dict):
            continue
        groups.setdefault(str(row.get(series_key, "Trend") if series_key else "Trend"), []).append(row)
    values = [_num(row.get(y_key)) for rows in groups.values() for row in rows]
    max_value = max(values or [1])
    min_value = min(values or [0])
    span = max(max_value - min_value, 1)
    width, height = 460, 220
    paths = []
    legend = []
    for idx, (name, rows) in enumerate(list(groups.items())[:5]):
        rows = sorted(rows, key=lambda row: str(row.get(x_key)))
        points = []
        for row_index, row in enumerate(rows):
            x = 36 + (row_index / max(1, len(rows) - 1)) * (width - 70)
            y = 170 - ((_num(row.get(y_key)) - min_value) / span * 130)
            points.append(f"{x:.1f},{y:.1f}")
        color = PALETTE[idx % len(PALETTE)]
        paths.append(f'<polyline points="{" ".join(points)}" fill="none" stroke="{color}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>')
        legend.append(f'<circle cx="{38 + idx * 88}" cy="202" r="4" fill="{color}"/><text x="{46 + idx * 88}" y="206" font-size="9" fill="#475569">{html.escape(_truncate(name, 12))}</text>')
    return f'<svg viewBox="0 0 {width} {height}" role="img"><line x1="34" y1="174" x2="430" y2="174" stroke="#cbd5e1"/><line x1="34" y1="30" x2="34" y2="174" stroke="#cbd5e1"/>{"".join(paths)}{"".join(legend)}</svg>'


def _donut_svg(chart: dict[str, Any], *, donut: bool) -> str:
    raw_data = chart.get("data") or []
    data = raw_data[:8] if isinstance(raw_data, list) else []
    x_key = chart.get("x_key") or chart.get("x")
    y_key = chart.get("y_key") or chart.get("y")
    total = sum(max(0, _num(row.get(y_key))) for row in data if isinstance(row, dict)) or 1
    start = -90.0
    parts = []
    legend = []
    for idx, row in enumerate(data):
        value = max(0, _num(row.get(y_key)))
        angle = value / total * 360
        end = start + angle
        color = PALETTE[idx % len(PALETTE)]
        parts.append(f'<path d="{_arc_path(110, 110, 78, start, end)}" fill="none" stroke="{color}" stroke-width="34"/>')
        legend.append(f'<rect x="225" y="{32 + idx * 20}" width="10" height="10" rx="2" fill="{color}"/><text x="242" y="{41 + idx * 20}" font-size="10" fill="#475569">{html.escape(_truncate(_fmt(row.get(x_key)), 22))} ({html.escape(_fmt(round(value / total * 100, 1)))}%)</text>')
        start = end
    center = '<circle cx="110" cy="110" r="44" fill="white"/>' if donut else ""
    return f'<svg viewBox="0 0 460 220" role="img">{"".join(parts)}{center}{"".join(legend)}</svg>'


def _arc_path(cx: float, cy: float, radius: float, start_angle: float, end_angle: float) -> str:
    if end_angle - start_angle >= 359.9:
        end_angle = start_angle + 359.9
    start = _polar(cx, cy, radius, end_angle)
    end = _polar(cx, cy, radius, start_angle)
    large = 1 if end_angle - start_angle > 180 else 0
    return f"M {start[0]:.3f} {start[1]:.3f} A {radius} {radius} 0 {large} 0 {end[0]:.3f} {end[1]:.3f}"


def _polar(cx: float, cy: float, radius: float, angle: float) -> tuple[float, float]:
    radians = math.radians(angle)
    return cx + radius * math.cos(radians), cy + radius * math.sin(radians)


def _chart_rows(chart: dict[str, Any]) -> list[list[str]]:
    raw_data = chart.get("data") or []
    data = raw_data if isinstance(raw_data, list) else []
    x_key = chart.get("x_key") or chart.get("x")
    y_key = chart.get("y_key") or chart.get("y")
    series_key = chart.get("series_key")
    columns = [key for key in [x_key, series_key, y_key] if key]
    if not columns:
        return []
    return [[str(column) for column in columns]] + [[_fmt(row.get(column)) for column in columns] for row in data[:12] if isinstance(row, dict)]


def _reportlab_chart_drawing(chart: dict[str, Any]) -> Any | None:
    try:
        from reportlab.graphics.shapes import Circle, Drawing, Line, PolyLine, Rect, String
        from reportlab.lib import colors
    except Exception:
        return None
    data = chart.get("data") or []
    if not isinstance(data, list) or not data:
        return None
    chart_type = str(chart.get("type", "bar")).lower()
    x_key = chart.get("x_key") or chart.get("x")
    y_key = chart.get("y_key") or chart.get("y")
    if not x_key or not y_key:
        return None
    if chart_type == "line":
        rows = [row for row in data if isinstance(row, dict)][:18]
        values = [_num(row.get(y_key)) for row in rows]
        if len(values) < 2:
            return None
        drawing = Drawing(460, 170)
        drawing.add(Line(35, 25, 430, 25, strokeColor=colors.HexColor("#cbd5e1")))
        drawing.add(Line(35, 25, 35, 145, strokeColor=colors.HexColor("#cbd5e1")))
        min_value = min(values)
        span = max(max(values) - min_value, 1)
        points = []
        for index, value in enumerate(values):
            x = 40 + (index / max(1, len(values) - 1)) * 370
            y = 30 + ((value - min_value) / span) * 105
            points.extend([x, y])
        drawing.add(PolyLine(points, strokeColor=colors.HexColor("#3b82f6"), strokeWidth=2.5))
        for index in range(0, len(points), 2):
            drawing.add(Circle(points[index], points[index + 1], 2.8, fillColor=colors.HexColor("#8b5cf6"), strokeColor=None))
        return drawing
    rows = [row for row in data if isinstance(row, dict)][:8]
    values = [abs(_num(row.get(y_key))) for row in rows]
    max_value = _chart_scale(values)
    drawing = Drawing(460, max(90, 24 + len(rows) * 20))
    for index, row in enumerate(rows):
        y = drawing.height - 26 - index * 20
        value = _num(row.get(y_key))
        width = max(2, min(250, abs(value) / max_value * 250))
        color = colors.HexColor(PALETTE[index % len(PALETTE)] if value >= 0 else "#f43f5e")
        drawing.add(String(0, y + 2, _truncate(_fmt(row.get(x_key)), 18), fontSize=8, fillColor=colors.HexColor("#475569")))
        drawing.add(Rect(125, y, width, 10, rx=3, ry=3, fillColor=color, strokeColor=None))
        drawing.add(String(130 + width, y + 2, _fmt(value), fontSize=8, fillColor=colors.HexColor("#0f172a")))
    return drawing


def _safe_facts(facts: dict[str, Any], xai_output: dict[str, Any]) -> dict[str, Any]:
    return {
        "dataset_profile": facts.get("dataset_profile"),
        "semantic_map": facts.get("semantic_map"),
        "business_metrics": facts.get("business_metrics"),
        "product_analysis": facts.get("product_analysis"),
        "food_analysis": facts.get("food_analysis"),
        "data_quality": facts.get("data_quality"),
        "trends": facts.get("trends"),
        "prediction": facts.get("prediction"),
        "xai": xai_output or facts.get("xai"),
        "warnings": facts.get("warnings"),
        "recommendations": facts.get("recommendations"),
    }


def _chart_is_renderable(chart: Any) -> bool:
    if not isinstance(chart, dict):
        return False
    is_valid, _reason = validate_chart_spec(chart)
    return is_valid


def _is_food_dataset(facts: dict[str, Any]) -> bool:
    semantic = facts.get("semantic_map") or {}
    profile = facts.get("dataset_profile") or {}
    return semantic.get("dataset_type") == "food_dataset" or profile.get("dataset_type") == "food_dataset"


def _prediction_text(prediction: dict[str, Any]) -> str:
    if prediction.get("status") != "complete":
        return prediction.get("reason") or "Prediction/modeling was not run."
    metrics = prediction.get("test_metrics") or {}
    text = (
        f"{prediction.get('selected_model')} was trained for {prediction.get('target_column')} "
        f"as a {prediction.get('task_type')} task. Test metrics: {metrics}."
    )
    limitations = " ".join(str(item) for item in prediction.get("limitations", []))
    return f"{text} {limitations}".strip()


def _xai_text(xai: dict[str, Any], prediction: dict[str, Any]) -> str:
    if not xai.get("top_features"):
        return "XAI could not be generated because the model did not expose valid feature importance."
    warnings = " ".join(str(item) for item in xai.get("warnings", []))
    leakage = " ".join(str(item) for item in prediction.get("limitations", []) if "leakage" in str(item).lower())
    return (
        f"Method used: {xai.get('method')}. Top features: {', '.join(xai.get('top_features', []))}. "
        f"{xai.get('plain_english_explanation', '')} {warnings} {leakage}"
    ).strip()


def _focused_sales_context(business: dict[str, Any]) -> str:
    lines = []
    if business.get("top_categories"):
        leader = business["top_categories"][0]
        lines.append(f"{leader.get('category')} is top category by revenue with {leader.get('revenue')}.")
    if business.get("top_categories_by_transactions"):
        leader = business["top_categories_by_transactions"][0]
        lines.append(f"{leader.get('category')} is top category by transaction count with {leader.get('transaction_count')} rows.")
    if business.get("top_regions"):
        leader = business["top_regions"][0]
        lines.append(f"{leader.get('region')} is top region by revenue with {leader.get('revenue')}.")
    return " ".join(lines) or "Top category and region context were unavailable."


def _manual_pdf(lines: list[str]) -> bytes:
    page_lines = []
    for line in lines:
        clean = _ascii(_plain(str(line)))
        wrapped = re.findall(r".{1,88}(?:\s+|$)", clean) or [clean]
        page_lines.extend(item.strip() for item in wrapped)
    pages = [page_lines[idx : idx + 48] for idx in range(0, len(page_lines), 48)] or [["DataVerse report"]]
    objects = ["1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj"]
    kids = []
    content_ids = []
    for page_index, page in enumerate(pages):
        page_obj = 3 + page_index * 2
        content_obj = page_obj + 1
        kids.append(f"{page_obj} 0 R")
        content_ids.append(content_obj)
        stream_lines = ["BT /F1 10 Tf 50 760 Td 14 TL"]
        for line in page:
            escaped = line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
            stream_lines.append(f"({escaped}) Tj T*")
        stream_lines.append("ET")
        stream = "\n".join(stream_lines)
        objects.append(f"{page_obj} 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 {3 + len(pages) * 2} 0 R >> >> /Contents {content_obj} 0 R >> endobj")
        objects.append(f"{content_obj} 0 obj << /Length {len(stream.encode('latin-1', errors='ignore'))} >> stream\n{stream}\nendstream endobj")
    font_obj = 3 + len(pages) * 2
    objects.insert(1, f"2 0 obj << /Type /Pages /Kids [{' '.join(kids)}] /Count {len(pages)} >> endobj")
    objects.append(f"{font_obj} 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj")
    body = "%PDF-1.4\n"
    offsets = [0]
    for obj in objects:
        offsets.append(len(body))
        body += obj + "\n"
    xref_at = len(body)
    xref = ["xref", f"0 {len(objects) + 1}", "0000000000 65535 f "]
    xref.extend(f"{offset:010d} 00000 n " for offset in offsets[1:])
    trailer = f"\ntrailer << /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF"
    return (body + "\n".join(xref) + trailer).encode("latin-1", errors="ignore")


def _strip_fence(text: str) -> str:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
    return cleaned


def _plain(value: str) -> str:
    return re.sub(r"<[^>]+>", " ", html.unescape(str(value))).replace("\n", " ")


def _ascii(value: str) -> str:
    return value.encode("latin-1", errors="ignore").decode("latin-1", errors="ignore")


def _fmt(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float):
        return f"{value:,.2f}".rstrip("0").rstrip(".")
    if isinstance(value, int):
        return f"{value:,}"
    return str(value)


def _num(value: Any) -> float:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return 0.0
    return number if math.isfinite(number) else 0.0


def _chart_scale(values: list[float]) -> float:
    return max([value for value in values if value > 0] or [1.0])


def _truncate(value: str, length: int) -> str:
    return value if len(value) <= length else value[: max(0, length - 3)] + "..."
